modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/mrshmllow/BetterRecipeBook/issues"
license = "MIT"

[[mods]]
modId = "brb"
version = "${version}"
displayName = "Better Recipe Book"
authors = "marshmallow"
credits = "ruvaldak, Felix14-v2, buiawpkgew1, TauCubed, MehradN, notlin4"
description = '''
Adds some quality of life changes to the recipe book
'''
logoFile = "icon.png"

[[dependencies.brb]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brb]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brb]]
modId = "architectury"
mandatory = true
versionRange = "[11,)"
ordering = "AFTER"
side = "BOTH"
