modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/mrshmllow/BetterRecipeBook/issues"
license = "MIT"

[[mods]]
modId = "brb"
version = "${version}"
displayName = "Better Recipe Book"
authors = "marshmallow"
credits = "ruvaldak, Felix14-v2, buiawpkgew1, TauCubed, MehradN, notlin4"
description = '''
Adds some quality of life changes to the recipe book
'''
logoFile = "icon.png"

[[dependencies.brb]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.brb]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.brb]]
modId = "architectury"
type = "required"
versionRange = "[13,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "mixins.brb.json"

[[mixins]]
config = "mixins.brb-common.json"

[[mixins]]
config = "mixins.brb-common-compat.json"

